name: CI Tecno-Repuestos

# Eventos que disparan la automatización
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Entorno de ejecución (Linux)

    steps:
      # 1. Descarga el repositorio al entorno de CI
      - name: Descargar repositorio
        uses: actions/checkout@v3

      # 2. Configura el entorno de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Instala las dependencias (Express, Jest, Supertest)
      - name: Instalar dependencias
        run: npm install

      # 4. Ejecuta las pruebas automatizadas (Unitarias e Integración)
      - name: Ejecutar pruebas
        run: npm test